### ISSUE TITLE
[FEATURE] Game tracking UI

### ISSUE THREAD

**Issue by shazxrin** [very-indecisive-studios/tracktgt-website#1]
### **Feature description**

This feature allows users to track games. Games to be tracked will have the following tracked information:

- Hours played
- Platform (e.g PS4, PC, Switch)
- Format Owned (i.e Digital, Physical)
- Status (i.e Currently Playing, Playing, Paused, Planning)
- Game Ownership (i.e Owned, Loaned, Subscription (e.g Xbox Game Pass), Wishlist)

Users can add tracked game from a game page (/home/games/$gameId). Users can view all, edit and delete tracked game from the game dashboard page (/home/games).

### **Describe the feature deliverables**

- [x] Game tracking
  - [x] Reusable modal pop up component for adding tracked game information
  - [x] Individual game page
    - [x] Add game to be tracked (via modal pop up)
  - [x] Game dashboard page
    - [x] View all tracked games in table form
      - [x] Separated by tracked status (individual table for Currently Playing and another for etc.)
      - [x] Each table is paged (up to 10 rows)
      - [x] Each tracked game row will show
        - Small cover image
        - Title
        - Hours played
        - Platform
        - Game Format
        - Game Ownership
        - Edit button
    - [x] Delete tracked game (via modal pop up)
    - [x] Modify tracked game's tracked information (via modal pop up)
