### ISSUE TITLE
[FEATURE] Books tracking UI

### ISSUE THREAD

**Issue by shazxrin** [very-indecisive-studios/tracktgt-website#17]
### **Feature description**

This feature allows users to track books. Books to be tracked will have the following tracked information:

- Chapters Read
- Format Owned (i.e Digital, Physical)
- Status (i.e Completed, Reading, Paused, Planning)
- Ownership (i.e Owned, Loaned, Wishlist)

Users can add tracked book from a book page (/home/books/$bookId). Users can view all, edit and delete tracked book from the book dashboard page (/home/books).

### **Describe the feature deliverables**

- [ ] Book tracking
  - [ ] Reusable modal pop up component for adding tracked book information
  - [ ] Individual book page
    - [ ] Add book to be tracked (via modal pop up)
  - [ ] Book dashboard page
    - [ ] View all tracked books in table form
      - [ ] Separated by tracked status (individual table for Reading and another for etc.)
      - [ ] Each table is paged (up to 5 rows)
      - [ ] Each tracked book row will show
        - Small cover image
        - Title
        - Chapters Read
        - Format Owned
        - Ownership
        - Edit button
    - [ ] Delete tracked book (via modal pop up)
    - [ ] Modify tracked book's tracked information (via modal pop up)
