### ISSUE TITLE
[FEATURE] Shows tracking UI

### ISSUE THREAD

**Issue by Mehvin** [very-indecisive-studios/tracktgt-website#19]
### **Feature description**

This feature allows users to track shows. Shows to be tracked will have the following tracked information:

- Episodes Watched (For movies, 1 - watched & 0 - not watched)
- Status (i.e Completed, Watching, Paused, Planning)
- Show Type (Movie or Series)

Users can add tracked show from a show page (/home/shows/$showId). Users can view all, edit and delete tracked show from the show dashboard page (/home/shows).

### **Describe the feature deliverables**

- [x] Show tracking
  - [x] Reusable modal pop up component for adding tracked show information
  - [x] Individual show page
    - [x] Add show to be tracked (via modal pop up)
  - [x] Show dashboard page
    - [x] View all tracked shows in table form
      - [x] Separated by tracked status (individual table for Watching and another for etc.)
      - [x] Each table is paged (up to 5 rows)
      - [x] Each tracked show row will show
        - Small cover image
        - Title
        - Episodes Watched
        - Show Type
        - Edit button
    - [x] Delete tracked show (via modal pop up)
    - [x] Modify tracked show 's tracked information (via modal pop up)
